[project]
name = "mcp-multi-service-server"
version = "0.1.0"
description = "A multi-service server using uv."
requires-python = ">=3.12"
dependencies = [
  "echo",    # tham chiếu tới package `echo` trong workspace
  "time",
]

