[project]
name = "echo"
version = "0.1.0"
description = "A simple echo service"
requires-python = ">=3.12"
dependencies = [
  "mcp",
  "aiohttp"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]