[project]
name = "mcp-framework"
version = "0.1.0"
description = "A multi-service server using uv."
requires-python = ">=3.12"
dependencies = [
  "fastapi", 
  "uvicorn",
  "pydantic",
  "pydantic-settings"
]
